#!/bin/sh -e

case "$1" in
  'configure')
    install -d -m 0600 /var/lib/sectpmctl/objects
    install -d -m 0600 /var/lib/sectpmctl/keys
    install -d /var/lib/sectpmctl/scripts
    install -d /etc/sectpmctl
    install -m 0755 /usr/lib/sectpmctl/boot.conf /etc/sectpmctl/boot.conf
    if [ ! -f /var/lib/sectpmctl/kernel_extra_options ]; then
      install -m 1640 /usr/share/sectpmctl/examples/kernel_extra_options.example /var/lib/sectpmctl/kernel_extra_options
      chattr +i /var/lib/sectpmctl/kernel_extra_options
    fi
    ;;
esac

#DEBHELPER#
