#!/bin/sh

set -e

exec </dev/null >&2

# Path's
SECTPMCTL_KEYS="/var/lib/sectpmctl/keys"
SECTPMCTL_BOOT="/boot/efi"
SECTPMCTL_EFI="/EFI/sectpmctl"
SECTPMCTL_EFI_DIR="${SECTPMCTL_BOOT}${SECTPMCTL_EFI}"

if [ ! -d "${SECTPMCTL_EFI_DIR}" ]; then
  echo 'sectpmctl boot inactive'
  exit 0
fi

command="${0}"
version="${1}"

case "${command}" in
  */kernel/postinst.d/*)
    set -- $DEB_MAINT_PARAMS
    mode="${1#\'}"
    mode="${mode%\'}"
    case ":${mode}" in
      :|:configure)
        sectpmctl boot update --kernel "${version}"
  	;;
    esac
    ;;
  */kernel/postrm.d/*)
    set -- $DEB_MAINT_PARAMS
    mode="${1#\'}"
    mode="${mode%\'}"
    case ":${mode}" in
      :|:remove)
        sectpmctl boot remove --kernel "${version}"
  	;;
    esac
    ;;
  */initramfs/post-update.d/*)
    eval set -- "${DPKG_MAINTSCRIPT_PACKAGE}"
    mode="${1#\'}"
    mode="${mode%\'}"
    case "${mode}" in
      linux-image-*)
        ;;
      *)
        sectpmctl boot update --kernel "${version}"
        ;;
    esac
    ;;
esac

exit 0

